name: Demo Eslint
on:
  pull_request:
    branches:
      - main
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v
        
      - name: Install dependencies
        run: npm ci
        if: success()

      - name: Run Eslint
        run: npm run lint
        if: success()

      - name: Prettify Code
        run: npm run format
        if: success()

      - name: Run Jest
        run: npm run test
        if: success()

      - name: Run build
        run: npm run build
        


      
