name: Demo Eslint
on:
  pull_request:
    branches:
      - main
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Prettify Code
        run: npm run format
      - name: Run Jest
        run: npm run test

  build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: npm run build
