name: Demo Eslint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run Eslint
      run: npm run lint

